[package]
name = "simple-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
proxy-common = { path = "../proxy-common" }
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
url = { workspace = true }
futures = "0.3"
serde_json = "1"
wreq = { version = "5", features = ["stream"] }
wreq-util = { version = "2", features = ["emulation-serde"] }
